#!/bin/bash

CURDIR=$(dirname $(realpath "${BASH_SOURCE[0]}"))
source "$CURDIR/cache"

cluster_id1=$(uuidgen)
cluster_id2=$(uuidgen)
cluster_id3=$(uuidgen)

"$CURDIR/run" $* --node 0 --cluster-id "$cluster_id1" --cluster-id "$cluster_id2" --cluster-id "$cluster_id3" --base_channel_port 10000 --disable-console &
vm1_pid=$!

"$CURDIR/run" $* --node 1 --cluster-id "$cluster_id1" --cluster-id "$cluster_id2" --cluster-id "$cluster_id3" --base_channel_port 11000 --disable-console &
vm2_pid=$!

"$CURDIR/run" $* --node 2 --cluster-id "$cluster_id1" --cluster-id "$cluster_id2" --cluster-id "$cluster_id3" --base_channel_port 12000 --disable-console &
vm3_pid=$!

wait $vm1_pid $vm2_pid $vm3_pid
